version: '2'
services:
    http:
        image: nginx
        restart: always
        links:
            - registry
            - registry_ui
        ports:
            - 127.0.0.1:5080:80
        volumes:
            - ./_docker/nginx.conf/:/etc/nginx/conf.d/default.conf:ro

    registry:
        image: registry:2
        restart: always
        environment:
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
        volumes:
            - data:/var/lib/registry

    registry_ui:
        image: konradkleine/docker-registry-frontend:v2
        restart: always
        links:
            - registry:registry
        environment:
            - ENV_DOCKER_REGISTRY_HOST=registry
            - ENV_DOCKER_REGISTRY_PORT=5000

volumes:
    data:
